# https://ls-lint.org

ls:
  .dir: camelCase | regex:^[_\.].*
  .js: camelCase | regex:^[_\.].*
  .ts: camelCase | regex:^[_\.].*
  .d.ts: camelCase | regex:^[_\.].* | regex:^auto-imports
  .png: snake_case | kebab-case
  .gif: snake_case
  .jpg: snake_case
  .jpeg: snake_case
  .svg: kebab-case
  .vue: camelCase | regex:^App$
  .scss: camelCase | regex:^[_\.].*
  .json: camelCase | regex:^[_\.].* | regex:^tsconfig.*
  .config.mjs: camelCase
  .config.ts: camelCase

  src/components:
    .dir: camelCase | regex:^components
    .vue: PascalCase | regex:^index

  src/{views,layout}/**/components:
    .vue: PascalCase | regex:^index

ignore:
  - node_modules
  - .git
  - .vscode
  - dist
  - coverage
  - public/static
