name: autofix.ci # must named autofix.ci

on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint:oxlint
      - run: pnpm run lint:script --fix

      - uses: autofix-ci/action@v1.3.2
        with:
          commit-message: 'chore: autofix by ci'
